version: "3.9"
services:
  discord-jira:
    build: ./
    image: sirh/discord-jira:latest
    container_name: discord-jira
    restart: unless-stopped
    ports:
      - "6969:6969"
    stdin_open: true
    tty: true